perl metricCalc.pl A1
perl metricCalc.pl A2
perl metricCalc.pl A3
perl metricCalc.pl B1
perl metricCalc.pl B2
perl metricCalc.pl B3
perl metricCalc.pl C1
perl metricCalc.pl C2
perl metricCalc.pl C3
perl metricCalc.pl C4
perl metricCalc.pl C5
perl metricCalc.pl C6
perl metricCalc.pl C7
perl metricCalc.pl C8
perl metricCalc.pl C9
perl metricCalc.pl C10
perl metricCalc.pl D1
perl metricCalc.pl D2
perl metricCalc.pl D3
perl metricCalc.pl D4
perl metricCalc.pl D5
perl metricCalc.pl D6
perl metricCalc.pl D7
perl metricCalc.pl D8
perl metricCalc.pl D9
perl metricCalc.pl D10
perl metricCalc.pl E1
perl metricCalc.pl E2
